version: '3.9'
services:
  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    container_name: backend
    volumes:
      - uploads_medical:/app/uploads
    networks:
      - network_shared

networks:
  network_shared:
    driver: bridge
    external: true  # Nếu network đã tồn tại  

volumes:
  uploads_medical:




